# Generated by Django 3.0.8 on 2020-09-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='Appl_Date',
            field=models.DateField(null=True),
        ),
    ]
