# Generated by Django 3.0.8 on 2020-09-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_User', '0002_response_appl_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='Appl_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
