# Generated by Django 3.0.8 on 2020-09-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_User', '0003_auto_20200928_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='Service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
