# Generated by Django 3.0.8 on 2020-09-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_User', '0004_auto_20200928_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='Status',
            field=models.CharField(default='Submitted', max_length=50, null=True),
        ),
    ]
