# Generated by Django 3.0.8 on 2020-10-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_User', '0005_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='Language',
            field=models.CharField(default='Null', max_length=200, null=True),
        ),
    ]
