# Generated by Django 3.0.8 on 2020-09-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Login',
            fields=[
                ('EMail', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Designation', models.CharField(max_length=20)),
                ('Addre_1', models.CharField(max_length=70)),
                ('Addre_2', models.CharField(max_length=70)),
                ('Addre_3', models.CharField(max_length=70)),
                ('Pin', models.CharField(blank=True, default='', max_length=20)),
                ('Mobile', models.IntegerField()),
                ('Password', models.CharField(max_length=70)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('last_login', models.DateField()),
            ],
        ),
    ]
