# Generated by Django 3.0.8 on 2020-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200928_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='Status',
            field=models.CharField(default='Active', max_length=70),
        ),
    ]
