# Generated by Django 3.0.8 on 2020-09-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templ_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMail', models.CharField(max_length=300)),
                ('Mobile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Templ_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=70)),
                ('Owner', models.CharField(max_length=200)),
                ('Added_On', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Templ_Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=1000)),
                ('Image', models.ImageField(default='default.jpg', upload_to='Technologies')),
                ('Status', models.CharField(max_length=70)),
                ('Owner', models.CharField(max_length=200)),
                ('Added_On', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('Issue', models.CharField(blank=True, max_length=50, null=True)),
                ('Desc', models.TextField(max_length=200)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User_Login')),
            ],
        ),
    ]
