# Generated by Django 3.0.8 on 2020-09-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_templ_contact_templ_services_templ_technologies_user_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templ_contact',
            name='EMail',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='templ_contact',
            name='Mobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
