# Generated by Django 3.0.8 on 2020-09-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20200929_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='last_login',
            field=models.DateTimeField(),
        ),
    ]
