# Generated by Django 3.0.8 on 2020-09-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20200929_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Owner', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=70)),
                ('Date', models.DateField(auto_now=True)),
                ('Description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Client_Name', models.CharField(max_length=100)),
                ('Client_Contact', models.CharField(max_length=50, null=True)),
                ('Client_Email', models.CharField(max_length=100, null=True)),
                ('URL', models.CharField(max_length=500)),
                ('Status', models.CharField(max_length=70)),
                ('Date', models.DateField(auto_now=True)),
                ('Description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
