# Generated by Django 3.0.8 on 2020-10-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_academic_projects_business_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Update', models.CharField(max_length=100)),
                ('Owner', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
