# Generated by Django 3.0.7 on 2020-10-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_updations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templ_contact',
            name='EMail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='templ_contact',
            name='Mobile',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
