# Generated by Django 3.0.8 on 2020-10-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20201002_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='templ_services',
            name='Description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
