# Generated by Django 3.0.7 on 2020-10-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_templ_services_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_login',
            name='Password',
        ),
    ]
