# Generated by Django 3.0.8 on 2020-10-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_user_login_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='updations',
            name='Change',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
