# Generated by Django 3.0.8 on 2020-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_updations_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='Designation',
            field=models.CharField(max_length=30),
        ),
    ]
